[package]
name = "counter-timer"
version = "0.2.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
enum-iterator = "1.4"

[dev-dependencies]
num-traits = "0.2"
num-derive = "0.3"
